import { test, expect } from '@playwright/test';

// Generated by --dry-run in place of a real implement phase (attempt 2).
// __dry_run_verdict__: pass
test('rejects an invalid password [migrated:rejects_an_invalid_password]', async ({ page }) => {
  // covers rejects_an_invalid_password:shows-error-banner
  await page.goto('http://localhost:4000');
  // Dry-run fixture body — no assertion here actually executes; VERIFY
  // reads the verdict marker above instead of launching a browser.
});
