// Dry-run mode replaces exactly two things: the model (which would write the
// target file in IMPLEMENT) and the browser (which VERIFY would launch).
// Everything else in the loop — gates, checks, evidence hashing, assertion
// parity, git commits, the transition table — runs for real, against real
// files this module writes. That is deliberate: a reader should see the
// actual mechanism operate, not a mocked-out narration of it.
//
// Four scripted scenarios live here, each illustrating one engine behavior
// a plain "everything passes" demo wouldn't exercise:
//   - login_valid    passes first attempt — the happy path.
//   - login_invalid  fails once, passes on retry — a converging retry.
//   - list_filter    fails twice with the *same* signature — thrash, dropped
//                    before the attempt budget is even spent.
//   - checkout_flow  passes VERIFY but fails REVIEW's scripted check first
//                    (a stray .only left in the file); the fix is generated
//                    on attempt 2. Also carries one deliberately dropped
//                    assertion, to exercise that half of the evidence
//                    contract too.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MigrationAdapter } from "./adapter.js";
import type { Unit } from "./types.js";

interface ScenarioAttempt {
  pass: boolean;
  failDetail?: string;
  hasOnly?: boolean;
}

const SCENARIOS: Record<string, ScenarioAttempt[]> = {
  logs_in_with_valid_credentials: [{ pass: true }],
  rejects_an_invalid_password: [
    { pass: false, failDetail: "expect(errorBanner).toBeVisible() — locator resolved to 0 elements" },
    { pass: true },
  ],
  filters_tasks_by_status: [
    { pass: false, failDetail: "locator '#status-filter' not found on page" },
    { pass: false, failDetail: "locator '#status-filter' not found on page" },
  ],
  completes_a_multi_step_checkout_flow: [
    { pass: true, hasOnly: true },
    { pass: true, hasOnly: false },
  ],
};

const CHECKOUT_UNIT_ID = "completes_a_multi_step_checkout_flow";

const DEFAULT_ATTEMPT: ScenarioAttempt = { pass: true };

export function scenarioFor(unitId: string, attemptNumber: number): ScenarioAttempt {
  const attempts = SCENARIOS[unitId];
  if (!attempts) return DEFAULT_ATTEMPT;
  return attempts[Math.min(attemptNumber, attempts.length - 1)];
}

export function scenarioAttemptCount(unitId: string): number {
  return SCENARIOS[unitId]?.length ?? 1;
}

const VERDICT_MARKER = "__dry_run_verdict__";

/** Writes the fixture "migration" a real IMPLEMENT phase would have produced
 * for this attempt. The verdict marker is what dry-run VERIFY reads back —
 * nothing here is hidden adapter state, it's the file on disk, same as a
 * real run. */
export async function implementDryRun(unit: Unit, attemptNumber: number, targetFile: string): Promise<void> {
  const attempt = scenarioFor(unit.id, attemptNumber);
  const verdictLine = attempt.pass
    ? `// ${VERDICT_MARKER}: pass`
    : `// ${VERDICT_MARKER}: fail:${attempt.failDetail}`;

  const coverLines = unit.sourceAssertions.map((assertion, i) => {
    const isLastOfCheckout = unit.id === CHECKOUT_UNIT_ID && i === unit.sourceAssertions.length - 1;
    return isLastOfCheckout
      ? `  // dropped ${assertion}: demo app has no email-confirmation step to assert against`
      : `  // covers ${assertion}`;
  });

  const source = `import { test, expect } from '@playwright/test';

// Generated by --dry-run in place of a real implement phase (attempt ${attemptNumber + 1}).
${verdictLine}
test${attempt.hasOnly ? ".only" : ""}('${unit.sourceName} ${unit.tag}', async ({ page }) => {
${coverLines.join("\n")}
  await page.goto('http://localhost:4000');
  // Dry-run fixture body — no assertion here actually executes; VERIFY
  // reads the verdict marker above instead of launching a browser.
});
`;

  await mkdir(path.dirname(targetFile), { recursive: true });
  await writeFile(targetFile, source, "utf8");
}

async function writeCannedReport(unit: Unit, attemptNumber: number, passed: boolean, failDetail?: string): Promise<string> {
  const reportPath = path.posix.join("tasks", "reports", `${unit.id}-dryrun-${attemptNumber + 1}.json`);
  await mkdir(path.dirname(reportPath), { recursive: true });
  const report = {
    note: "Generated by --dry-run to exercise the real hashing/parity code without launching a browser.",
    config: { dryRun: true },
    stats: { expected: passed ? 1 : 0, unexpected: passed ? 0 : 1, skipped: 0 },
    suites: passed
      ? []
      : [
          {
            specs: [
              {
                file: `${unit.id}.spec.ts`,
                tests: [
                  {
                    results: [
                      {
                        status: "failed",
                        error: { message: failDetail ?? "dry-run simulated failure", location: { file: `${unit.id}.spec.ts`, line: 7 } },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
  };
  await writeFile(reportPath, JSON.stringify(report, null, 2), "utf8");
  return reportPath;
}

/** Wraps a real adapter, substituting only verifyUnit (no browser) — the
 * rest (enumerateUnits, recordEvidence, principles, evidenceCommand) is the
 * exact same code a real run uses. */
export function makeDryRunAdapter(real: MigrationAdapter): MigrationAdapter {
  return {
    enumerateUnits: real.enumerateUnits,
    recordEvidence: real.recordEvidence,
    principles: real.principles,
    evidenceCommand: real.evidenceCommand,
    async verifyUnit(unit, targetFile) {
      const { readFile } = await import("node:fs/promises");
      const src = await readFile(targetFile, "utf8");
      const marker = src.match(new RegExp(`${VERDICT_MARKER}:\\s*(pass|fail)(?::(.*))?`));
      const attemptNumber = Number(src.match(/attempt (\d+)/)?.[1] ?? "1") - 1;
      const passed = marker?.[1] === "pass";
      const failDetail = marker?.[2]?.trim();
      const reportPath = await writeCannedReport(unit, attemptNumber, passed, failDetail);
      return { passed, signature: passed ? undefined : failDetail, reportPath };
    },
  };
}
